//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tathkīr_WPF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tathkīr_WPF.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Prayer Thikr.
        /// </summary>
        public static string After_Prayer_Thikr {
            get {
                return ResourceManager.GetString("After_Prayer_Thikr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alllahumm slla ealaa sayidina muhammad.
        /// </summary>
        public static string Alllahumm_slla_ealaa_sayidina_muhammad {
            get {
                return ResourceManager.GetString("Alllahumm_slla_ealaa_sayidina_muhammad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asr.
        /// </summary>
        public static string Asr {
            get {
                return ResourceManager.GetString("Asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athan Thikr .
        /// </summary>
        public static string Athan_Thikr {
            get {
                return ResourceManager.GetString("Athan_Thikr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athkar.
        /// </summary>
        public static string Athkar {
            get {
                return ResourceManager.GetString("Athkar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athkar Reminder.
        /// </summary>
        public static string Athkar_Reminder {
            get {
                return ResourceManager.GetString("Athkar_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedtime Thikr.
        /// </summary>
        public static string Bedtime_Thikr {
            get {
                return ResourceManager.GetString("Bedtime_Thikr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        public static string Bookmark {
            get {
                return ResourceManager.GetString("Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the reader.
        /// </summary>
        public static string Choose_The_Reader {
            get {
                return ResourceManager.GetString("Choose_The_Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhuhr.
        /// </summary>
        public static string Dhuhr {
            get {
                return ResourceManager.GetString("Dhuhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eating Thikr.
        /// </summary>
        public static string Eating_Thikr {
            get {
                return ResourceManager.GetString("Eating_Thikr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering/Leaving Bathroom Thikr .
        /// </summary>
        public static string Entering_Leaving_Bathroom_Thikr {
            get {
                return ResourceManager.GetString("Entering/Leaving_Bathroom_Thikr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening Thikr.
        /// </summary>
        public static string Evening_Thikr {
            get {
                return ResourceManager.GetString("Evening_Thikr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        public static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajr.
        /// </summary>
        public static string Fajr {
            get {
                return ResourceManager.GetString("Fajr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you read your Athkar today?.
        /// </summary>
        public static string Have_you_read_your_Athkar_today {
            get {
                return ResourceManager.GetString("Have_you_read_your_Athkar_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isha.
        /// </summary>
        public static string Isha {
            get {
                return ResourceManager.GetString("Isha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time for.
        /// </summary>
        public static string It_s_Time_For {
            get {
                return ResourceManager.GetString("It\'s_Time_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumua.
        /// </summary>
        public static string Jumua {
            get {
                return ResourceManager.GetString("Jumua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La allah ala ant subhanak anna kunt min alzaalimina.
        /// </summary>
        public static string La_allah_ala_ant_subhanak_anna_kunt_min_alzaalimina {
            get {
                return ResourceManager.GetString("La_allah_ala_ant_subhanak_anna_kunt_min_alzaalimina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hawl wala quwwat alla biallahi.
        /// </summary>
        public static string La_hawl_wala_quwwat_alla_biallahi {
            get {
                return ResourceManager.GetString("La_hawl_wala_quwwat_alla_biallahi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Third.
        /// </summary>
        public static string Last_Third {
            get {
                return ResourceManager.GetString("Last_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on repeat.
        /// </summary>
        public static string Looping_Off {
            get {
                return ResourceManager.GetString("Looping_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looping On.
        /// </summary>
        public static string Looping_On {
            get {
                return ResourceManager.GetString("Looping_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maghrib.
        /// </summary>
        public static string Maghrib {
            get {
                return ResourceManager.GetString("Maghrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight.
        /// </summary>
        public static string Midnight {
            get {
                return ResourceManager.GetString("Midnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning Thikr.
        /// </summary>
        public static string Morning_Thikr {
            get {
                return ResourceManager.GetString("Morning_Thikr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosque Thikr.
        /// </summary>
        public static string Mosque_Thikr {
            get {
                return ResourceManager.GetString("Mosque_Thikr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prayer.
        /// </summary>
        public static string Prayer {
            get {
                return ResourceManager.GetString("Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prayer is approaching.
        /// </summary>
        public static string Prayer_Is_Approaching {
            get {
                return ResourceManager.GetString("Prayer_Is_Approaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayer Thikr.
        /// </summary>
        public static string Prayer_Thikr {
            get {
                return ResourceManager.GetString("Prayer_Thikr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayer Times.
        /// </summary>
        public static string Prayer_Times {
            get {
                return ResourceManager.GetString("Prayer_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran.
        /// </summary>
        public static string Quran {
            get {
                return ResourceManager.GetString("Quran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Time.
        /// </summary>
        public static string Repeat_Time {
            get {
                return ResourceManager.GetString("Repeat_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or select city.
        /// </summary>
        public static string Search_Or_Select_City {
            get {
                return ResourceManager.GetString("Search_Or_Select_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or select country.
        /// </summary>
        public static string Search_Or_Select_Country {
            get {
                return ResourceManager.GetString("Search_Or_Select_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        public static string Select_Location {
            get {
                return ResourceManager.GetString("Select_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subhan allah, alhamd lilhi, allah akbar, la alah ala allah.
        /// </summary>
        public static string Subhan_allah_alhamd_lilhi_allah_akbar_la_alah_ala_allah {
            get {
                return ResourceManager.GetString("Subhan_allah_alhamd_lilhi_allah_akbar_la_alah_ala_allah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subhan allah wabihamdihi, subhan allh aleazimi.
        /// </summary>
        public static string Subhan_allah_wabihamdihi_subhan_allh_aleazimi {
            get {
                return ResourceManager.GetString("Subhan_allah_wabihamdihi_subhan_allh_aleazimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duha.
        /// </summary>
        public static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tathkīr.
        /// </summary>
        public static string Tathkir {
            get {
                return ResourceManager.GetString("Tathkir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time for.
        /// </summary>
        public static string The_Time_For {
            get {
                return ResourceManager.GetString("The_Time_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time till.
        /// </summary>
        public static string Time_Till {
            get {
                return ResourceManager.GetString("Time_Till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times per day.
        /// </summary>
        public static string Times_Per_Day {
            get {
                return ResourceManager.GetString("Times_Per_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake-up Thikr.
        /// </summary>
        public static string Wake_up_Thikr {
            get {
                return ResourceManager.GetString("Wake-up_Thikr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string Widgets {
            get {
                return ResourceManager.GetString("Widgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wudu Thikr.
        /// </summary>
        public static string Wudu_Thikr {
            get {
                return ResourceManager.GetString("Wudu_Thikr", resourceCulture);
            }
        }
    }
}
