//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tathkīr_WPF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tathkīr_WPF.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available.
        /// </summary>
        public static string A_New_Version_Is_Available {
            get {
                return ResourceManager.GetString("A_New_Version_Is_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert time.
        /// </summary>
        public static string Alert_Time {
            get {
                return ResourceManager.GetString("Alert_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alllahumm slla ealaa sayidina muhammad.
        /// </summary>
        public static string Alllahumm_slla_ealaa_sayidina_muhammad {
            get {
                return ResourceManager.GetString("Alllahumm_slla_ealaa_sayidina_muhammad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the application?.
        /// </summary>
        public static string Are_You_Sure_You_Want_To_Close_The_Application {
            get {
                return ResourceManager.GetString("Are_You_Sure_You_Want_To_Close_The_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asr.
        /// </summary>
        public static string Asr {
            get {
                return ResourceManager.GetString("Asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athkar.
        /// </summary>
        public static string Athkar {
            get {
                return ResourceManager.GetString("Athkar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athkar Reminder.
        /// </summary>
        public static string Athkar_Reminder {
            get {
                return ResourceManager.GetString("Athkar_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Athan.
        /// </summary>
        public static string Before_Athan {
            get {
                return ResourceManager.GetString("Before_Athan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        public static string Bookmark {
            get {
                return ResourceManager.GetString("Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the reader.
        /// </summary>
        public static string Choose_The_Reader {
            get {
                return ResourceManager.GetString("Choose_The_Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        public static string Close_Application {
            get {
                return ResourceManager.GetString("Close_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Main Window.
        /// </summary>
        public static string Close_Main_Window {
            get {
                return ResourceManager.GetString("Close_Main_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhuhr.
        /// </summary>
        public static string Dhuhr {
            get {
                return ResourceManager.GetString("Dhuhr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Alert.
        /// </summary>
        public static string Disabled_Alert {
            get {
                return ResourceManager.GetString("Disabled_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable alert.
        /// </summary>
        public static string Enable_Alert {
            get {
                return ResourceManager.GetString("Enable_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        public static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajr.
        /// </summary>
        public static string Fajr {
            get {
                return ResourceManager.GetString("Fajr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you read your Athkar today?.
        /// </summary>
        public static string Have_you_read_your_Athkar_today {
            get {
                return ResourceManager.GetString("Have_you_read_your_Athkar_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string Is {
            get {
                return ResourceManager.GetString("Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isha.
        /// </summary>
        public static string Isha {
            get {
                return ResourceManager.GetString("Isha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time for.
        /// </summary>
        public static string It_s_Time_For {
            get {
                return ResourceManager.GetString("It\'s_Time_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumua.
        /// </summary>
        public static string Jumua {
            get {
                return ResourceManager.GetString("Jumua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La allah ala ant subhanak anna kunt min alzaalimina.
        /// </summary>
        public static string La_allah_ala_ant_subhanak_anna_kunt_min_alzaalimina {
            get {
                return ResourceManager.GetString("La_allah_ala_ant_subhanak_anna_kunt_min_alzaalimina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La hawl wala quwwat alla biallahi.
        /// </summary>
        public static string La_hawl_wala_quwwat_alla_biallahi {
            get {
                return ResourceManager.GetString("La_hawl_wala_quwwat_alla_biallahi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Third.
        /// </summary>
        public static string Last_Third {
            get {
                return ResourceManager.GetString("Last_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch on system startup.
        /// </summary>
        public static string Launch_On_System_Startup {
            get {
                return ResourceManager.GetString("Launch_On_System_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on repeat.
        /// </summary>
        public static string Looping_Off {
            get {
                return ResourceManager.GetString("Looping_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looping On.
        /// </summary>
        public static string Looping_On {
            get {
                return ResourceManager.GetString("Looping_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maghrib.
        /// </summary>
        public static string Maghrib {
            get {
                return ResourceManager.GetString("Maghrib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight.
        /// </summary>
        public static string Midnight {
            get {
                return ResourceManager.GetString("Midnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Prayer.
        /// </summary>
        public static string Next_Prayer {
            get {
                return ResourceManager.GetString("Next_Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Athan.
        /// </summary>
        public static string On_Athan {
            get {
                return ResourceManager.GetString("On_Athan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current settings will be reset. Please restart the application to activate the new settings..
        /// </summary>
        public static string OnReset {
            get {
                return ResourceManager.GetString("OnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current settings will be saved. Please restart the application to activate the new settings..
        /// </summary>
        public static string OnSave {
            get {
                return ResourceManager.GetString("OnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the releases page?.
        /// </summary>
        public static string Open_The_Releases_Page {
            get {
                return ResourceManager.GetString("Open_The_Releases_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string Personalization {
            get {
                return ResourceManager.GetString("Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prayer.
        /// </summary>
        public static string Prayer {
            get {
                return ResourceManager.GetString("Prayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prayer is approaching.
        /// </summary>
        public static string Prayer_Is_Approaching {
            get {
                return ResourceManager.GetString("Prayer_Is_Approaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayer Reminder.
        /// </summary>
        public static string Prayer_Reminder {
            get {
                return ResourceManager.GetString("Prayer_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayer Times.
        /// </summary>
        public static string Prayer_Times {
            get {
                return ResourceManager.GetString("Prayer_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Info.
        /// </summary>
        public static string Privacy_Info {
            get {
                return ResourceManager.GetString("Privacy_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran.
        /// </summary>
        public static string Quran {
            get {
                return ResourceManager.GetString("Quran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Time.
        /// </summary>
        public static string Repeat_Time {
            get {
                return ResourceManager.GetString("Repeat_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or select city.
        /// </summary>
        public static string Search_Or_Select_City {
            get {
                return ResourceManager.GetString("Search_Or_Select_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search or select country.
        /// </summary>
        public static string Search_Or_Select_Country {
            get {
                return ResourceManager.GetString("Search_Or_Select_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string Select_Language {
            get {
                return ResourceManager.GetString("Select_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        public static string Select_Location {
            get {
                return ResourceManager.GetString("Select_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tasbeeh Limit.
        /// </summary>
        public static string Select_Tasbeeh_Limit {
            get {
                return ResourceManager.GetString("Select_Tasbeeh_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Theme.
        /// </summary>
        public static string Select_Theme {
            get {
                return ResourceManager.GetString("Select_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Main Window on system startup.
        /// </summary>
        public static string Show_Main_Window {
            get {
                return ResourceManager.GetString("Show_Main_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notifications.
        /// </summary>
        public static string Show_Notifications {
            get {
                return ResourceManager.GetString("Show_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Widget on startup.
        /// </summary>
        public static string Show_Widget {
            get {
                return ResourceManager.GetString("Show_Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subhan allah, alhamd lilhi, allah akbar, la alah ala allah.
        /// </summary>
        public static string Subhan_allah_alhamd_lilhi_allah_akbar_la_alah_ala_allah {
            get {
                return ResourceManager.GetString("Subhan_allah_alhamd_lilhi_allah_akbar_la_alah_ala_allah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subhan allah wabihamdihi, subhan allh aleazimi.
        /// </summary>
        public static string Subhan_allah_wabihamdihi_subhan_allh_aleazimi {
            get {
                return ResourceManager.GetString("Subhan_allah_wabihamdihi_subhan_allh_aleazimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duha.
        /// </summary>
        public static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasbeeh.
        /// </summary>
        public static string Tasbeeh {
            get {
                return ResourceManager.GetString("Tasbeeh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tathkīr.
        /// </summary>
        public static string Tathkir {
            get {
                return ResourceManager.GetString("Tathkir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time for.
        /// </summary>
        public static string The_Time_For {
            get {
                return ResourceManager.GetString("The_Time_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thikr Reminder.
        /// </summary>
        public static string Thikr_Reminder {
            get {
                return ResourceManager.GetString("Thikr_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time till.
        /// </summary>
        public static string Time_Till {
            get {
                return ResourceManager.GetString("Time_Till", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times per day.
        /// </summary>
        public static string Times_Per_Day {
            get {
                return ResourceManager.GetString("Times_Per_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string Widgets {
            get {
                return ResourceManager.GetString("Widgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
